version: '3'
services:
  test:
    image: llaunes:1.0
    expose:
      - "80"
    environment:
      - HOST_NAME=gp1f4a8.fjeclot.net
  
  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test
    ports:
      - "80:8000"

